name: gan_project
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9.9
  - numpy=1.22.3
  - requests=2.27.1
  - black=22.3.0
  - dlib=19.23.1
  - pytorch=1.10.0
  - scikit-image=0.19.2
  - pip=22.0.4
  - pillow=9.0.1
  - matplotlib=3.5.1
  - ipython=8.2.0
  - torchvision=0.2.1
  - scipy=1.5.3
  - transformers=4.16.2
  - pip:
    - opencv-python==4.5.5.64
    - tensorflow-gpu==2.8.0
    - keras==2.8.0
    - pytorch-fid==0.2.1
    - lpips==0.1.4
    - tensorflow-addons==0.16.1